# Generated by Django 3.0.6 on 2020-05-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='someuser',
            name='display_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
