# Generated by Django 3.0.6 on 2020-05-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_someuser_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='someuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
